#define FLAG_DEF(flag) flag##_FLAG

#define FLAG(flag) (1ull << flag##_FLAG)
#define FLAG_CLEAR(flag) (~FLAG(flag))
#define FLAG_NOT(flag) FLAG_CLEAR(flag)

#define FLAGS(pfx, ...) (0ull __VA_OPT__(|FLAGS_0(pfx, __VA_ARGS__)))
#define FLAGS_CLEAR(pfx, ...) (~(FLAGS(pfx, __VA_ARGS__)))
#define FLAGS_NOT(...) FLAGS_CLEAR(__VA_ARGS__)

#define FLAGS_0(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_1(pfx, __VA_ARGS__))
#define FLAGS_1(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_2(pfx, __VA_ARGS__))
#define FLAGS_2(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_3(pfx, __VA_ARGS__))
#define FLAGS_3(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_4(pfx, __VA_ARGS__))
#define FLAGS_4(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_5(pfx, __VA_ARGS__))
#define FLAGS_5(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_6(pfx, __VA_ARGS__))
#define FLAGS_6(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_7(pfx, __VA_ARGS__))
#define FLAGS_7(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_8(pfx, __VA_ARGS__))
#define FLAGS_8(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_9(pfx, __VA_ARGS__))
#define FLAGS_9(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_10(pfx, __VA_ARGS__))
#define FLAGS_10(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_11(pfx, __VA_ARGS__))
#define FLAGS_11(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_12(pfx, __VA_ARGS__))
#define FLAGS_12(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_13(pfx, __VA_ARGS__))
#define FLAGS_13(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_14(pfx, __VA_ARGS__))
#define FLAGS_14(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_15(pfx, __VA_ARGS__))
#define FLAGS_15(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_16(pfx, __VA_ARGS__))
#define FLAGS_16(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_17(pfx, __VA_ARGS__))
#define FLAGS_17(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_18(pfx, __VA_ARGS__))
#define FLAGS_18(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_19(pfx, __VA_ARGS__))
#define FLAGS_19(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_20(pfx, __VA_ARGS__))
#define FLAGS_20(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_21(pfx, __VA_ARGS__))
#define FLAGS_21(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_22(pfx, __VA_ARGS__))
#define FLAGS_22(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_23(pfx, __VA_ARGS__))
#define FLAGS_23(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_24(pfx, __VA_ARGS__))
#define FLAGS_24(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_25(pfx, __VA_ARGS__))
#define FLAGS_25(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_26(pfx, __VA_ARGS__))
#define FLAGS_26(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_27(pfx, __VA_ARGS__))
#define FLAGS_27(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_28(pfx, __VA_ARGS__))
#define FLAGS_28(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_29(pfx, __VA_ARGS__))
#define FLAGS_29(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_30(pfx, __VA_ARGS__))
#define FLAGS_30(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_31(pfx, __VA_ARGS__))
#define FLAGS_31(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_32(pfx, __VA_ARGS__))
#define FLAGS_32(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_33(pfx, __VA_ARGS__))
#define FLAGS_33(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_34(pfx, __VA_ARGS__))
#define FLAGS_34(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_35(pfx, __VA_ARGS__))
#define FLAGS_35(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_36(pfx, __VA_ARGS__))
#define FLAGS_36(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_37(pfx, __VA_ARGS__))
#define FLAGS_37(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_38(pfx, __VA_ARGS__))
#define FLAGS_38(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_39(pfx, __VA_ARGS__))
#define FLAGS_39(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_40(pfx, __VA_ARGS__))
#define FLAGS_40(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_41(pfx, __VA_ARGS__))
#define FLAGS_41(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_42(pfx, __VA_ARGS__))
#define FLAGS_42(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_43(pfx, __VA_ARGS__))
#define FLAGS_43(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_44(pfx, __VA_ARGS__))
#define FLAGS_44(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_45(pfx, __VA_ARGS__))
#define FLAGS_45(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_46(pfx, __VA_ARGS__))
#define FLAGS_46(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_47(pfx, __VA_ARGS__))
#define FLAGS_47(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_48(pfx, __VA_ARGS__))
#define FLAGS_48(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_49(pfx, __VA_ARGS__))
#define FLAGS_49(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_50(pfx, __VA_ARGS__))
#define FLAGS_50(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_51(pfx, __VA_ARGS__))
#define FLAGS_51(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_52(pfx, __VA_ARGS__))
#define FLAGS_52(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_53(pfx, __VA_ARGS__))
#define FLAGS_53(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_54(pfx, __VA_ARGS__))
#define FLAGS_54(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_55(pfx, __VA_ARGS__))
#define FLAGS_55(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_56(pfx, __VA_ARGS__))
#define FLAGS_56(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_57(pfx, __VA_ARGS__))
#define FLAGS_57(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_58(pfx, __VA_ARGS__))
#define FLAGS_58(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_59(pfx, __VA_ARGS__))
#define FLAGS_59(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_60(pfx, __VA_ARGS__))
#define FLAGS_60(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_61(pfx, __VA_ARGS__))
#define FLAGS_61(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_62(pfx, __VA_ARGS__))
#define FLAGS_62(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_63(pfx, __VA_ARGS__))
#define FLAGS_63(pfx, flag, ...) FLAG(pfx##_##flag)__VA_OPT__(|FLAGS_64(pfx, __VA_ARGS__))
#define FLAGS_64(pfx, flag, ...) FLAGS_TOO_MANY_ARGUMENTS
